version: 2
jobs:
  build:
    docker:
      - image: nvidia/cuda:10.0-cudnn7-devel-centos7

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
