version: 2
jobs:
  build:
    docker:
      - image: nvidia/cuda:10.0-cudnn7-devel-centos7

    steps:
      - checkout

      - run:
          name: build
          command: chmod +x cmake/build_server_centos.sh && ./cmake/build_server_centos.sh

      - run:
          name: Print the Current Time
          command: date
